import {expect,test} from "@playwright/test";
import {execFileSync} from "node:child_process";

const adminEmail=process.env.DEV_ADMIN_EMAIL||"admin@example.test";
const adminPassword=process.env.DEV_ADMIN_PASSWORD||"correct-horse";
function localDateTime(minutesFromNow:number){const date=new Date(Date.now()+minutesFromNow*60_000);const pad=(value:number)=>String(value).padStart(2,"0");return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`}

test("administrator, candidate, canvas, completion, and evaluation smoke path",async({browser,page})=>{
  const diagnostics:string[]=[];
  page.on("requestfailed",request=>diagnostics.push(`${request.method()} ${request.url()} :: ${request.failure()?.errorText||"unknown"}`));
  page.on("console",message=>{if(message.type()==="error")diagnostics.push(`console ${message.text().slice(0,160)}`)});
  page.on("response",response=>{if(response.url().endsWith("/auth/login"))diagnostics.push(`login-status ${response.status()}`)});
  const candidateName=`Browser Smoke Candidate ${Date.now()}`;
  await page.context().grantPermissions(["clipboard-read","clipboard-write"]);
  const backendHealth=await page.goto(`${process.env.E2E_API_URL||"http://localhost:8000"}/health`);
  expect(backendHealth?.status()).toBe(200);
  await page.goto("/login");
  await page.getByLabel("Email").fill(adminEmail);
  await page.getByLabel("Password").fill(adminPassword);
  await page.getByRole("button",{name:"Sign in"}).click();
  try { await expect(page).toHaveURL(/\/admin\/sessions$/); } catch (error) { console.log("smoke diagnostics", diagnostics); throw error; }

  await page.goto("/admin/sessions");
  await page.getByLabel("Candidate name").fill(candidateName);
  await page.getByLabel("Scheduled time").fill(localDateTime(1));
  await page.getByLabel("Duration").fill("30");
  await page.getByRole("button",{name:"Create"}).click();
  await expect(page.getByText(candidateName,{exact:true})).toBeVisible();
  await expect(page.getByRole("listitem").filter({hasText:candidateName}).getByRole("link",{name:"View Session"})).toBeVisible();
  await page.getByLabel("Search sessions").fill(candidateName.toLowerCase());
  await expect(page.getByRole("link",{name:"View Session"})).toBeVisible();
  await page.getByLabel("Status filter").selectOption("scheduled");
  await expect(page.getByRole("link",{name:"View Session"})).toBeVisible();
  await page.getByRole("button",{name:"Clear criteria"}).click();
  await page.getByRole("listitem").filter({hasText:candidateName}).getByRole("link",{name:"View Session"}).click();
  await page.getByRole("button",{name:"Generate invite"}).click();
  const inviteInput=page.getByLabel("Invite URL");
  await expect(inviteInput).toBeVisible();
  const inviteUrl=await inviteInput.inputValue();
  await page.getByRole("button",{name:"Copy"}).click();
  await expect.poll(()=>page.evaluate(()=>navigator.clipboard.readText())).toBe(inviteUrl);

  const candidateContext=await browser.newContext({permissions:["clipboard-read","clipboard-write"]});
  const candidatePage=await candidateContext.newPage();
  let candidateCanvasTokenResponses=0;
  let candidateCanvasToken="";
  candidatePage.on("response",async response=>{if(response.url().endsWith("/canvas-token")){candidateCanvasTokenResponses+=1;candidateCanvasToken=(await response.json()).token}});
  await candidatePage.goto(inviteUrl);
  await candidatePage.getByRole("link",{name:"Enter session"}).click();
  await expect(candidatePage.getByRole("heading",{name:"Live interview"})).toBeVisible();
  await expect(candidatePage.locator("iframe[title=\"Collaborative canvas\"]")).toBeVisible();
  await candidatePage.waitForTimeout(4500);
  expect(candidateCanvasTokenResponses).toBe(1);
  const sessionUrl=candidatePage.url();
  await page.goto(sessionUrl);
  await expect(page.getByRole("heading",{name:"Live interview"})).toBeVisible();
  await expect(page.locator("iframe[title=\"Collaborative canvas\"]")).toBeVisible();
  const candidateFrame=candidatePage.frameLocator("iframe[title=\"Collaborative canvas\"]");
  const adminFrame=page.frameLocator("iframe[title=\"Collaborative canvas\"]");
  await candidateFrame.getByRole("button",{name:"Rectangle"}).click();
  const candidateFrameBox=await candidatePage.locator("iframe[title=\"Collaborative canvas\"]").boundingBox();
  if(!candidateFrameBox) throw new Error("candidate canvas frame is not visible");
  await candidatePage.mouse.move(candidateFrameBox.x+120,candidateFrameBox.y+140);
  await candidatePage.mouse.down();
  await candidatePage.mouse.move(candidateFrameBox.x+260,candidateFrameBox.y+240,{steps:4});
  await candidatePage.mouse.up();
  await candidateFrame.getByRole("button",{name:"Save XML"}).click();
  await expect(adminFrame.locator("#canvas > *")).toHaveCount(2);
  await expect(candidateFrame.locator("#canvas > *")).toHaveCount(2);
  await expect.poll(()=>candidateCanvasToken).not.toBe("");
  const crossSession=await candidatePage.request.get(`${process.env.E2E_CANVAS_SYNC_URL||"http://localhost:8787"}/drawio/rooms/not-this-session`,{headers:{Authorization:`Bearer ${candidateCanvasToken}`}});
  expect(crossSession.status()).toBe(403);
  await adminFrame.getByRole("button",{name:"Rectangle"}).click();
  const adminFrameBox=await page.locator("iframe[title=\"Collaborative canvas\"]").boundingBox();
  if(!adminFrameBox) throw new Error("admin canvas frame is not visible");
  await page.mouse.move(adminFrameBox.x+320,adminFrameBox.y+160);
  await page.mouse.down();
  await page.mouse.move(adminFrameBox.x+420,adminFrameBox.y+250,{steps:4});
  await page.mouse.up();
  await adminFrame.getByRole("button",{name:"Save XML"}).click();
  await expect(candidateFrame.locator("#canvas > *")).toHaveCount(3);
  await expect(adminFrame.locator("#canvas > *")).toHaveCount(3);
  execFileSync("docker",["compose","restart","canvas-sync"],{cwd:"..",timeout:30_000,stdio:"pipe"});
  await candidatePage.reload();
  await expect(candidatePage.locator("iframe[title=\"Collaborative canvas\"]")).toBeVisible();
  await expect(candidatePage.frameLocator("iframe[title=\"Collaborative canvas\"]").locator("#canvas > *")).toHaveCount(3);
  await candidatePage.getByRole("button",{name:"Leave"}).click();
  await expect(candidatePage).toHaveURL(/\/login$/);
  await page.getByRole("button",{name:"Finish session"}).click();
  await expect(page.getByRole("link",{name:"Open evaluation"})).toBeVisible();
  await candidatePage.goto(sessionUrl);
  await expect(candidatePage.getByText("This session has ended. You may leave this page.")).toBeVisible();
  await page.getByRole("link",{name:"Open evaluation"}).click();
  for(const category of ["problem solving","technical fundamentals","communication","collaboration"]){
    await page.getByLabel(`${category} rating`).selectOption("4");
    await page.getByLabel(`${category} rationale`).fill("Observed browser smoke evidence.");
  }
  await page.getByLabel("Overall rating").selectOption("4");
  await page.getByRole("button",{name:"Save evaluation"}).click();
  await expect(page.getByText("Evaluation saved")).toBeVisible();
  expect(diagnostics.filter(item=>!item.includes("token")&&!item.includes("password")).length).toBeLessThan(20);
  await candidateContext.close();
});
