import {useEffect,useState} from "react";
import {Link,useParams} from "react-router-dom";
import {Tldraw} from "tldraw";
import {useSync} from "@tldraw/sync";
import {canEndSession,expiryMessage,remainingMinutes} from "./presentation";

const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
async function request(path:string,init:RequestInit={}){const token=localStorage.getItem("admin_token")||localStorage.getItem("candidate_token");const response=await fetch(`${API}${path}`,{...init,headers:{"content-type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...(init.headers||{})}});if(!response.ok)throw new Error((await response.json().catch(()=>({detail:"Request failed"}))).detail);return response.json()}
function LiveCanvas({sessionId,token,canvasUrl}:{sessionId:string;token:string;canvasUrl:string}){const sync=useSync({uri:()=>`${canvasUrl.replace(/^http/,"ws")}/rooms/${encodeURIComponent(sessionId)}?token=${encodeURIComponent(token)}`,assets:{upload:async()=>{throw new Error("Asset uploads are not enabled for this MVP")},resolve:()=>null}});if(sync.status==="loading")return <div className="canvas-status">Connecting to the collaborative canvas…</div>;if(sync.status==="error")return <div className="canvas-status error">Canvas unavailable: {sync.error.message}</div>;return <div className="canvas-editor"><Tldraw store={sync.store}/></div>}

export function LiveWorkspace(){const {sessionId}=useParams();const [item,setItem]=useState<any>();const [canvasToken,setCanvasToken]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");const [extension,setExtension]=useState("15");const [now,setNow]=useState(Date.now());const canvasUrl=import.meta.env.VITE_CANVAS_SYNC_URL||"http://localhost:8787";const facilitator=Boolean(localStorage.getItem("admin_token"));const role=facilitator?"admin":"candidate";const authPrefix=facilitator?"/admin":"";async function load(){try{setItem(await request(`${authPrefix}/sessions/${sessionId}`))}catch(e){setError(String(e))}}useEffect(()=>{load();request(`${authPrefix}/sessions/${sessionId}/canvas-token`,{method:"POST"}).then(r=>setCanvasToken(r.token)).catch(e=>setError(String(e)));const timer=window.setInterval(()=>{setNow(Date.now());load()},2000);return()=>window.clearInterval(timer)},[sessionId,facilitator]);async function end(){try{await request(`/admin/sessions/${sessionId}/end`,{method:"POST"});setMessage("Session ended");load()}catch(e){setMessage(String(e))}}async function extend(){const minutes=Number(extension);if(!Number.isInteger(minutes)||minutes<1){setMessage("Enter a positive whole number of minutes");return}try{await request(`/admin/sessions/${sessionId}/extend`,{method:"POST",body:JSON.stringify({minutes})});setMessage(`Session extended by ${minutes} minutes`);load()}catch(e){setMessage(String(e))}}if(error)return <main className="card"><h1>Access denied</h1><p className="error">{error}</p></main>;if(!item||!canvasToken)return <main className="card"><p>Joining session…</p></main>;const remaining=remainingMinutes(item.end_at,now);return <main className="card live"><div className="live-heading"><div><h1>Live interview</h1><p>{item.candidate_name} · <strong>{item.state}</strong>{remaining!==null&&item.state!=="completed"&&<span> · {remaining} min remaining</span>}</p></div>{canEndSession(role,item.state)&&<button onClick={end}>End session</button>}</div>{item.state==="expired"&&<div className="controls"><strong>{expiryMessage(role)}</strong>{facilitator&&<><input aria-label="Extension minutes" type="number" min="1" value={extension} onChange={e=>setExtension(e.target.value)}/><button onClick={extend}>Extend session</button></>}</div>}{item.state==="completed"&&facilitator&&<Link className="button" to={`/admin/sessions/${sessionId}/evaluation`}>Open evaluation</Link>}{message&&<p className="status">{message}</p>}<LiveCanvas sessionId={sessionId!} token={canvasToken} canvasUrl={canvasUrl}/></main>}
