"""initial interview canvas schema"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    state=sa.Enum("scheduled","active","expired-pending-facilitator-action","completed",name="sessionstate")
    op.create_table("admin_users",sa.Column("id",sa.String(36),primary_key=True),sa.Column("email",sa.String(320),nullable=False,unique=True),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("role",sa.String(32),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False))
    op.create_table("interview_sessions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("candidate_name",sa.String(200),nullable=False),sa.Column("candidate_email",sa.String(320)),sa.Column("scheduled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("duration_minutes",sa.Integer(),nullable=False),sa.Column("state",state,nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("end_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("facilitator_id",sa.String(36),sa.ForeignKey("admin_users.id")))
    op.create_table("session_invites",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("interview_sessions.id"),nullable=False),sa.Column("token_hash",sa.String(64),nullable=False,unique=True),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("redeemed_at",sa.DateTime(timezone=True)),sa.Column("revoked",sa.Boolean(),nullable=False))
    op.create_table("session_participants",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("interview_sessions.id"),nullable=False),sa.Column("role",sa.String(32),nullable=False),sa.Column("display_name",sa.String(200),nullable=False),sa.Column("joined_at",sa.DateTime(timezone=True),nullable=False),sa.Column("left_at",sa.DateTime(timezone=True)))
    op.create_table("session_extensions",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("interview_sessions.id"),nullable=False),sa.Column("minutes",sa.Integer(),nullable=False),sa.Column("initiated_by",sa.String(36),sa.ForeignKey("admin_users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("scorecard_templates",sa.Column("id",sa.String(36),primary_key=True),sa.Column("name",sa.String(200),nullable=False),sa.Column("categories",sa.JSON(),nullable=False))
    op.create_table("evaluations",sa.Column("id",sa.String(36),primary_key=True),sa.Column("session_id",sa.String(36),sa.ForeignKey("interview_sessions.id"),nullable=False),sa.Column("evaluator_id",sa.String(36),sa.ForeignKey("admin_users.id"),nullable=False),sa.Column("recommendation",sa.String(40),nullable=False),sa.Column("overall_rating",sa.Integer()),sa.Column("overall_notes",sa.Text()),sa.Column("submitted_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("evaluation_scores",sa.Column("id",sa.String(36),primary_key=True),sa.Column("evaluation_id",sa.String(36),sa.ForeignKey("evaluations.id"),nullable=False),sa.Column("category",sa.String(100),nullable=False),sa.Column("rating",sa.Integer(),nullable=False),sa.Column("rationale",sa.Text(),nullable=False))
    op.create_table("evaluation_notes",sa.Column("id",sa.String(36),primary_key=True),sa.Column("evaluation_id",sa.String(36),sa.ForeignKey("evaluations.id"),nullable=False),sa.Column("author_id",sa.String(36),sa.ForeignKey("admin_users.id"),nullable=False),sa.Column("note",sa.Text(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("audit_events",sa.Column("id",sa.String(36),primary_key=True),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("actor_id",sa.String(36)),sa.Column("actor_role",sa.String(32)),sa.Column("session_id",sa.String(36)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False))
def downgrade():
    for table in ["audit_events","evaluation_notes","evaluation_scores","evaluations","scorecard_templates","session_extensions","session_participants","session_invites","interview_sessions","admin_users"]: op.drop_table(table)
    sa.Enum(name="sessionstate").drop(op.get_bind(),checkfirst=True)
