import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {MemoryRouter,Route,Routes} from "react-router-dom";
import {afterEach,describe,expect,it,vi} from "vitest";
import "@testing-library/jest-dom/vitest";
import {RouteGate} from "./routes/guards";
import {hasCompleteScores} from "./features/evaluation/validation";
import {canEndSession,expiryMessage,remainingMinutes} from "./features/interview/presentation";
import {SessionDetail} from "./features/admin/SessionDetail";
import {SessionDashboard} from "./features/admin/SessionDashboard";
import {LiveWorkspace} from "./features/interview/LiveWorkspace";

const syncState=vi.hoisted(()=>({current:{status:"synced-remote",store:{}} as any}));
vi.mock("@tldraw/sync",()=>({useSync:()=>syncState.current}));
vi.mock("tldraw",()=>({Tldraw:()=> <div data-testid="tldraw-editor">Canvas editor</div>}));
import {SessionEvaluation} from "./features/evaluation/SessionEvaluation";

const Login=()=> <h1>Administrator login</h1>;
describe("route boundaries",()=>{it("renders the login boundary for unauthenticated users",()=>{render(<MemoryRouter><Login/></MemoryRouter>);expect(screen.getByRole("heading",{name:"Administrator login"})).toBeVisible();});});
describe("authorization states",()=>{it("shows pending authorization",()=>{render(<MemoryRouter><RouteGate authorized={false} pending/></MemoryRouter>);expect(screen.getByText("Authorizing session…")).toBeVisible();});it("redirects denied access to login",()=>{render(<MemoryRouter initialEntries={["/admin"]}><RouteGate authorized={false}><p>secret</p></RouteGate></MemoryRouter>);expect(screen.queryByText("secret")).not.toBeInTheDocument();});});
describe("interview and evaluation rules",()=>{it("requires every score and rationale",()=>{const categories=[{name:"communication"},{name:"technical"}];expect(hasCompleteScores(categories,{communication:{rating:4,rationale:"clear"}})).toBe(false);expect(hasCompleteScores(categories,{communication:{rating:4,rationale:"clear"},technical:{rating:3,rationale:"evidence"}})).toBe(true)});it("keeps facilitator controls role-scoped and timer server-based",()=>{const now=Date.parse("2026-01-01T00:00:00Z");expect(canEndSession("candidate","active")).toBe(false);expect(canEndSession("admin","active")).toBe(true);expect(expiryMessage("candidate")).toContain("Waiting");expect(remainingMinutes("2026-01-01T00:14:01Z",now)).toBe(15)})});
describe("administrator session detail",()=>{afterEach(()=>{vi.restoreAllMocks();localStorage.clear()});it("renders scheduled details and reports save/copy feedback",async()=>{localStorage.setItem("admin_token","admin-token");const fetchMock=vi.fn().mockImplementation((url:string)=>{if(url.endsWith("/invites"))return Promise.resolve({ok:true,json:async()=>[{active:true}]});if(url.endsWith("/invite"))return Promise.resolve({ok:true,json:async()=>({url:"http://localhost:5173/invite/raw-token"})});return Promise.resolve({ok:true,json:async()=>({id:"session-1",candidate_name:"Candidate",candidate_email:"candidate@example.test",scheduled_at:"2026-01-01T12:00:00Z",duration_minutes:45,state:"scheduled"})})});vi.stubGlobal("fetch",fetchMock);Object.defineProperty(navigator,"clipboard",{value:{writeText:vi.fn().mockResolvedValue(undefined)},configurable:true});render(<MemoryRouter initialEntries={["/admin/sessions/session-1"]}><Routes><Route path="/admin/sessions/:sessionId" element={<SessionDetail/>}/></Routes></MemoryRouter>);expect(await screen.findByRole("heading",{name:"Candidate"})).toBeVisible();fireEvent.change(screen.getByLabelText("Duration"),{target:{value:"60"}});fireEvent.click(screen.getByRole("button",{name:"Save details"}));await waitFor(()=>expect(screen.getByText("Session details saved")).toBeVisible());expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining("/admin/sessions/session-1"),expect.objectContaining({method:"PATCH"}));fireEvent.click(screen.getByRole("button",{name:"Generate invite"}));await waitFor(()=>expect(screen.getByLabelText("Invite URL")).toBeVisible());fireEvent.click(screen.getByRole("button",{name:"Copy"}));await waitFor(()=>expect(screen.getByText("Invite copied")).toBeVisible())})});
describe("invite failure feedback",()=>{afterEach(()=>{vi.restoreAllMocks();localStorage.clear()});it("shows revoked state and clipboard fallback",async()=>{localStorage.setItem("admin_token","admin-token");vi.stubGlobal("fetch",vi.fn().mockImplementation((url:string)=>{if(url.endsWith("/invites"))return Promise.resolve({ok:true,json:async()=>[{active:false,revoked:true}]});if(url.endsWith("/invite"))return Promise.resolve({ok:true,json:async()=>({url:"http://localhost:5173/invite/raw-token"})});return Promise.resolve({ok:true,json:async()=>({id:"session-1",candidate_name:"Candidate",scheduled_at:"2026-01-01T12:00:00Z",duration_minutes:45,state:"scheduled"})})}));Object.defineProperty(navigator,"clipboard",{value:{writeText:vi.fn().mockRejectedValue(new Error("denied"))},configurable:true});render(<MemoryRouter initialEntries={["/admin/sessions/session-1"]}><Routes><Route path="/admin/sessions/:sessionId" element={<SessionDetail/>}/></Routes></MemoryRouter>);expect(await screen.findByText("Invite revoked, redeemed, or expired")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Generate invite"}));await waitFor(()=>expect(screen.getByLabelText("Invite URL")).toBeVisible());fireEvent.click(screen.getByRole("button",{name:"Copy"}));await waitFor(()=>expect(screen.getByText("Clipboard unavailable; copy the URL manually")).toBeVisible())})});
describe("completed-session evaluation",()=>{afterEach(()=>{vi.restoreAllMocks();localStorage.clear()});it("reloads a saved scorecard and confirms submission",async()=>{localStorage.setItem("admin_token","admin-token");const categories=["problem solving","technical fundamentals","communication","collaboration"].map(name=>({name,description:"Evidence"}));const saved={recommendation:"strong-hire",overall_rating:5,overall_notes:"Excellent",private_notes:["Private"],scores:categories.map(({name})=>({category:name,rating:4,rationale:"Observed"}))};const fetchMock=vi.fn().mockImplementation((url:string,init:RequestInit={})=>{if(url.endsWith("/scorecards/default"))return Promise.resolve({ok:true,json:async()=>categories});if(init.method==="POST")return Promise.resolve({ok:true,json:async()=>({id:"evaluation-1"})});return Promise.resolve({ok:true,json:async()=>saved})});vi.stubGlobal("fetch",fetchMock);render(<MemoryRouter initialEntries={["/admin/sessions/session-1/evaluation"]}><Routes><Route path="/admin/sessions/:sessionId/evaluation" element={<SessionEvaluation/>}/></Routes></MemoryRouter>);expect(await screen.findByDisplayValue("strong-hire")).toBeVisible();expect(screen.getByDisplayValue("Excellent")).toBeVisible();expect(screen.getByDisplayValue("Private")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Save evaluation"}));await waitFor(()=>expect(screen.getByText("Evaluation saved")).toBeVisible());expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining("/admin/sessions/session-1/evaluation"),expect.objectContaining({method:"POST"}))})});
describe("administrator session dashboard",()=>{afterEach(()=>{vi.restoreAllMocks();localStorage.clear()});it("validates required creation fields and renders the created session",async()=>{localStorage.setItem("admin_token","admin-token");let created=false;const fetchMock=vi.fn().mockImplementation((url:string,init:RequestInit={})=>{if(init.method==="POST"){created=true;return Promise.resolve({ok:true,json:async()=>({id:"session-1"})})}return Promise.resolve({ok:true,json:async()=>created?[{id:"session-1",candidate_name:"New Candidate",scheduled_at:"2026-01-01T12:00:00Z",duration_minutes:45,state:"scheduled"}]:[]})});vi.stubGlobal("fetch",fetchMock);render(<MemoryRouter><SessionDashboard/></MemoryRouter>);expect(await screen.findByRole("heading",{name:"Sessions"})).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"Create"}));expect(screen.getByLabelText("Candidate name")).toBeInvalid();fireEvent.change(screen.getByLabelText("Candidate name"),{target:{value:"New Candidate"}});fireEvent.change(screen.getByLabelText("Scheduled time"),{target:{value:"2026-01-01T12:00"}});fireEvent.click(screen.getByRole("button",{name:"Create"}));await waitFor(()=>expect(screen.getByText("New Candidate")).toBeVisible())})});
describe("live workspace",()=>{afterEach(()=>{vi.restoreAllMocks();localStorage.clear();syncState.current={status:"synced-remote",store:{}}});it("shows an authorized candidate the server timer without facilitator controls",async()=>{const endAt=new Date(Date.now()+10*60000).toISOString();localStorage.setItem("candidate_token","candidate-token");vi.stubGlobal("fetch",vi.fn().mockImplementation((url:string)=>{if(url.endsWith("/canvas-token"))return Promise.resolve({ok:true,json:async()=>({token:"canvas-token"})});return Promise.resolve({ok:true,json:async()=>({id:"session-1",candidate_name:"Candidate",state:"active",end_at:endAt})})}));render(<MemoryRouter initialEntries={["/session/session-1"]}><Routes><Route path="/session/:sessionId" element={<LiveWorkspace/>}/></Routes></MemoryRouter>);expect(await screen.findByRole("heading",{name:"Live interview"})).toBeVisible();expect(screen.getByText(/min remaining/)).toBeVisible();expect(screen.queryByRole("button",{name:"End session"})).not.toBeInTheDocument();expect(screen.getByTestId("tldraw-editor")).toBeVisible()});it("shows facilitator expiry controls and canvas recovery state",async()=>{localStorage.setItem("admin_token","admin-token");syncState.current={status:"error",error:new Error("connection lost")};vi.stubGlobal("fetch",vi.fn().mockImplementation((url:string)=>{if(url.endsWith("/canvas-token"))return Promise.resolve({ok:true,json:async()=>({token:"canvas-token"})});return Promise.resolve({ok:true,json:async()=>({id:"session-1",candidate_name:"Candidate",state:"expired",end_at:new Date().toISOString()})})}));render(<MemoryRouter initialEntries={["/session/session-1"]}><Routes><Route path="/session/:sessionId" element={<LiveWorkspace/>}/></Routes></MemoryRouter>);expect(await screen.findByText("Time expired. End or extend the session.")).toBeVisible();expect(screen.getByRole("button",{name:"Extend session"})).toBeVisible();expect(screen.getByText("Canvas unavailable: connection lost")).toBeVisible()})});
