import React,{FormEvent,useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter,Link,Navigate,Route,Routes,useNavigate,useParams} from "react-router-dom";
import {RouteGate} from "./routes/guards";
import {SessionDetail} from "./features/admin/SessionDetail";
import {SessionDashboard} from "./features/admin/SessionDashboard";
import {SessionEvaluation} from "./features/evaluation/SessionEvaluation";
import {LiveWorkspace} from "./features/interview/LiveWorkspace";
import {hasCompleteScores} from "./features/evaluation/validation";
import {canEndSession,expiryMessage,remainingMinutes} from "./features/interview/presentation";
import "./style.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:8000";
type Session={id:string;candidate_name:string;candidate_email?:string;scheduled_at:string;duration_minutes:number;state:string};
async function api(path:string,init:RequestInit={}){const token=localStorage.getItem("admin_token")||localStorage.getItem("candidate_token"); const headers={"content-type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}) ,...(init.headers||{})}; const r=await fetch(`${API}${path}`,{...init,headers}); if(!r.ok) throw new Error((await r.json().catch(()=>({detail:"Request failed"}))).detail); return r.json();}
const Shell=({children}:{children:React.ReactNode})=><div className="shell"><header><Link to="/admin">Interview Canvas</Link><nav><Link to="/admin/sessions">Sessions</Link><button onClick={()=>{localStorage.clear();location.href="/login"}}>Log out</button></nav></header>{children}</div>;
const Protected=({children}:{children:React.ReactNode})=><RouteGate authorized={Boolean(localStorage.getItem("admin_token"))}><Shell>{children}</Shell></RouteGate>;
function Login(){const nav=useNavigate(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); async function submit(e:FormEvent){e.preventDefault();try{const r=await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})});localStorage.setItem("admin_token",r.access_token);nav("/admin")}catch(e){setError(String(e))}} return <main className="card narrow"><h1>Administrator login</h1><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="error">{error}</p>}<button>Sign in</button></form></main>}
function Dashboard(){return <main className="card"><h1>Interview Canvas</h1><p>Manage interview sessions, candidate invitations, and evaluations.</p><Link className="button" to="/admin/sessions">Open sessions</Link></main>}
function Sessions(){const [items,setItems]=useState<Session[]>([]);const [error,setError]=useState("");const [name,setName]=useState("");const [when,setWhen]=useState("");const [duration,setDuration]=useState("45"); async function load(){try{setItems(await api("/admin/sessions"))}catch(e){setError(String(e))}} useEffect(()=>{load()},[]);async function create(e:FormEvent){e.preventDefault();try{await api("/admin/sessions",{method:"POST",body:JSON.stringify({candidate_name:name,scheduled_at:new Date(when).toISOString(),duration_minutes:Number(duration)})});setName("");setWhen("");load()}catch(e){setError(String(e))}} return <main className="card"><h1>Sessions</h1><form className="inline-form" onSubmit={create}><input placeholder="Candidate name" value={name} onChange={e=>setName(e.target.value)} required/><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} required/><input type="number" min="1" value={duration} onChange={e=>setDuration(e.target.value)}/><button>Create</button></form>{error&&<p className="error">{error}</p>}<ul className="sessions">{items.map(x=><li key={x.id}><Link to={`/admin/sessions/${x.id}`}>{x.candidate_name}</Link><span>{x.state} · {x.duration_minutes} min</span></li>)}</ul></main>}
function Invite(){const {token}=useParams();const [state,setState]=useState("loading");useEffect(()=>{api("/invites/redeem",{method:"POST",body:JSON.stringify({token})}).then(r=>{localStorage.setItem("candidate_token",r.candidate_token);setState(r.session_id)}).catch((e)=>setState(String(e).replace("Error: ","")))},[token]);return <main className="card narrow"><h1>Candidate invitation</h1>{state==="loading"?<p>Validating invitation…</p>:state.includes("expired")||state.includes("revoked")||state.includes("already-used")||state.includes("invalid")?<p className="error">{state}</p>:<><p>Invitation accepted.</p><Link className="button" to={`/session/${state}`}>Enter session</Link></>}</main>}
function Evaluation(){const {sessionId}=useParams();const [categories,setCategories]=useState<any[]>([]);const [scores,setScores]=useState<Record<string,{rating:number;rationale:string}>>({});const [recommendation,setRecommendation]=useState("hire");const [overallRating,setOverallRating]=useState("");const [overallNotes,setOverallNotes]=useState("");const [notes,setNotes]=useState("");const [message,setMessage]=useState("");useEffect(()=>{Promise.all([api("/scorecards/default"),api(`/admin/sessions/${sessionId}/evaluation`).catch(()=>null)]).then(([defaults,saved])=>{setCategories(defaults);if(saved){setRecommendation(saved.recommendation);setOverallRating(saved.overall_rating?String(saved.overall_rating):"");setOverallNotes(saved.overall_notes||"");setNotes((saved.private_notes||[]).join("\n"));setScores(Object.fromEntries(saved.scores.map((x:any)=>[x.category,{rating:x.rating,rationale:x.rationale}])))} }).catch(e=>setMessage(String(e)))},[sessionId]);async function submit(e:FormEvent){e.preventDefault();if(!hasCompleteScores(categories,scores)){setMessage("Complete every rating and rationale before saving");return}try{await api(`/admin/sessions/${sessionId}/evaluation`,{method:"POST",body:JSON.stringify({scores:categories.map(c=>({category:c.name,...scores[c.name]})),recommendation,overall_rating:overallRating?Number(overallRating):null,overall_notes:overallNotes,private_notes:notes})});setMessage("Evaluation saved")}catch(e){setMessage(String(e))}}return <main className="card"><h1>Evaluation</h1><form onSubmit={submit}>{categories.map(c=><fieldset key={c.name}><legend>{c.name}</legend><p>{c.description}</p><select required aria-label={`${c.name} rating`} value={scores[c.name]?.rating||""} onChange={e=>setScores({...scores,[c.name]:{...scores[c.name],rating:Number(e.target.value)}})}><option value="">Rating</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select><textarea required aria-label={`${c.name} rationale`} placeholder="Rationale" value={scores[c.name]?.rationale||""} onChange={e=>setScores({...scores,[c.name]:{...scores[c.name],rationale:e.target.value}})}/></fieldset>)}<label>Overall rating<select aria-label="Overall rating" value={overallRating} onChange={e=>setOverallRating(e.target.value)}><option value="">Optional</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>Overall notes<textarea value={overallNotes} onChange={e=>setOverallNotes(e.target.value)}/></label><label>Recommendation<select value={recommendation} onChange={e=>setRecommendation(e.target.value)}><option>hire</option><option>no-hire</option><option>strong-hire</option><option>strong-no-hire</option></select></label><label>Private notes<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button>Save evaluation</button></form>{message&&<p className="status">{message}</p>}</main>}
function App(){return <Routes><Route path="/login" element={<Login/>}/><Route path="/admin" element={<Protected><Dashboard/></Protected>}/><Route path="/admin/sessions" element={<Protected><SessionDashboard/></Protected>}/><Route path="/admin/sessions/:sessionId" element={<Protected><SessionDetail/></Protected>}/><Route path="/admin/sessions/:sessionId/evaluation" element={<Protected><SessionEvaluation/></Protected>}/><Route path="/invite/:token" element={<Invite/>}/><Route path="/session/:sessionId" element={<LiveWorkspace/>}/><Route path="*" element={<Navigate to="/admin" replace/>}/></Routes>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>);
